version: '2.0'

services:
  db:
    image: postgres
    restart: always
    # volumes:
    #   - /home/db:/var/lib/postgresql/data
    env_file: 
      - ./db.env
    environment:
      # POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"


  web:
    build: .
    image: micropyramid/django-crm:1
    env_file: 
      - ./db.env
    ports:
      - "8001:8000"
    depends_on:
      - db
    links:
      - db:db
