version: '2.0'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /home/db:/var/lib/postgresql/data
    env_file: 
      - ./db.env
    networks:
      - overlay
    ports:
      - 5431:5432
  web:
    build: .
    image: micropyramid/django-crm:1
    env_file: 
      - ./db.env
    ports:
      - "8001:8000"
    depends_on:
      - db
    links:
      - db:db
